### ISSUE TITLE
Not seeing names in usage.htm

### ISSUE THREAD

**Issue by maphew** [pyrovski/wrtbwmon#11]
I've generated a `users.txt` file and am using it when publishing, but there's no change to the html page. What should I be seeing? Is my users format is messed up?

```
## /opt/wrtbwmon/users.txt
00:AA:11:BB:22:BC,black-cisco-router
74:AA:11:BB:22:10,xps
BC:AA:11:BB:22:10,server
...
F8:AA:11:BB:22:D9,iPod-touch
10:AA:11:BB:22:4E,printer
```

```
/opt/sbin/wrtbwmon publish /tmp/usage.db /opt/share/www/custom/usage.htm /opt/wrtbwmon/users.txt
```

![2015-11-26 21_07_22-traffic](https://cloud.githubusercontent.com/assets/486200/11434531/abbfca76-9482-11e5-923f-48d8734049f9.png)

(As a general note, maybe instructions should refer to machine names as well as or instead of users, since the lookup is by ip and some devices have multiple users.)

**Comment by maphew** [comment]
Ahhh found it! The MAC addresses in users.txt need to be lower case.

**Comment by pyrovski** [comment]
I changed the code to allow upper-case or lower-case MACs.
