### ISSUE TITLE
IP not expanded correctly

### ISSUE THREAD

**Issue by sumitsemwal** [pyrovski/wrtbwmon#14]
Hi,

Thanks for the wonderful utility! It's certainly very useful! I am running the latest release of openwrt, and I see this kind of output: (I've obfuscated some personal details)

User    Download    Upload  Total   First seen  Last seen
cgi-bin index.html luci-static  1.934 G 298 M   2.232 G 01-02-2016_19:41:30 04-02-2016_17:00:15
ss-ubuntu   1.469 G 373 M   1.842 G 01-02-2016_19:41:29 04-02-2016_17:00:16
08:.....:a8 1.095 G 35 M    1.13 G  01-02-2016_19:41:29 03-02-2016_00:00:00
android-2......f5870fa  834 M   16 M    850 M   01-02-2016_21:00:00 04-02-2016_10:00:00
cgi-bin index.html luci-static  404 M   77 M    481 M   01-02-2016_19:41:30 04-02-2016_14:00:00
cgi-bin index.html luci-static  340 M   32 M    373 M   02-02-2016_20:00:00 04-02-2016_17:00:00

Is this something you've seen already, and would you please be able to help?

Best,
Sumit.

**Comment by pyrovski** [comment]
I just started a new job; I'm currently working with them to arrange permission to fix this. Thanks for your patience!

**Comment by pyrovski** [comment]
Can you add "set -x" to the top of the wrtbwmon script and send me the output of the update and publish commands?

**Comment by sumitsemwal** [comment]
Hi,

I have the output, but don't want to put it in public; if you can send me
your email ID, I'd be happy to. mine is sumu.ss@gmail.com

Best regards,
Sumit

On Thu, Feb 18, 2016 at 1:17 PM, Peter Bailey notifications@github.com
wrote:

> Can you add "set -x" to the top of the wrtbwmon script and send me the
> output of the update and publish commands?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pyrovski/wrtbwmon/issues/14#issuecomment-185583557.

## 

~me!

**Comment by pyrovski** [comment]
I believe d9eebcb3bece95b6a3bddd4b578722d4b938d1fd fixes this issue; please test the new version.

**Comment by sumitsemwal** [comment]
Hi,
It does make it better, thank you! I still have lots of nodes like 'localhost', so it would perhaps be good to add IP addresses as well?

**Comment by pyrovski** [comment]
I believe the most recent version has MAC and IP addresses in the mouseover
text.

**Comment by sumitsemwal** [comment]
yes, and thank you for that! :+1: you may please close this ticket if you'd like
