### ISSUE TITLE
iptables v1.4.21: host/network `eth1' not found when trying to use old usage.db

### ISSUE THREAD

**Issue by mw446391** [pyrovski/wrtbwmon#16]
Hi - I have updated my wrtbwmon script with rev 208c412.

I'm not sure which version I used before but I remember I installed the previous version on 17 JAN).

The new version works but I have problems getting it to work with my old usage.db.

When I tried an update, I get these errors:
root@OpenWrt:~# /transfer/wrtbwmon# wrtbwmon.sh update /tmp/usage.db
iptables v1.4.21: host/network `eth1' not found
Try`iptables -h' or 'iptables --help' for more information.
iptables v1.4.21: host/network `eth1' not found
Try`iptables -h' or 'iptables --help' for more information.

If I start with a fresh usage.db then all works:

root@OpenWrt:~# /transfer/wrtbwmon# rm /tmp/usage.db
root@OpenWrt:~# /transfer/wrtbwmon# wrtbwmon.sh setup /tmp/usage.db
root@OpenWrt:~# /transfer/wrtbwmon# wrtbwmon.sh update /tmp/usage.db
root@OpenWrt:~# 

But when I restore the old usage.db and try an update, then it fails again:

root@OpenWrt:~# /transfer/wrtbwmon# cp /tmp/usage.db-bak /tmp/usage.db
root@OpenWrt:~# /transfer/wrtbwmon# wrtbwmon.sh update /tmp/usage.db
iptables v1.4.21: host/network `eth1' not found
Try`iptables -h' or 'iptables --help' for more information.
iptables v1.4.21: host/network `eth1' not found
Try`iptables -h' or 'iptables --help' for more information.

Has there been a change in the DB layout since JAN? If not, how can I merge the old and new usage.db?

**Comment by pyrovski** [comment]
I don't recall if there was a change in the layout. Wrtbwmon is not
designed to migrate DB versions yet, but it's just a CSV file. The column
names are on the first line of the file.

On Tue, May 3, 2016 at 8:18 AM, mw446391 notifications@github.com wrote:

> Hi - I have updated my wrtbwmon script with rev 208c412
> https://github.com/pyrovski/wrtbwmon/commit/208c412fa4a8dca98c1791016e93642a7f3b70cc
> .
> 
> I'm not sure which version I used before but I remember I installed the
> previous version on 17 JAN).
> 
> The new version works but I have problems getting it to work with my old
> usage.db.
> 
> When I tried an update, I get these errors:
> root@OpenWrt:~# /transfer/wrtbwmon# wrtbwmon.sh update /tmp/usage.db
> iptables v1.4.21: host/network eth1' not found
> Tryiptables -h' or 'iptables --help' for more information.
> iptables v1.4.21: host/network eth1' not found
> Tryiptables -h' or 'iptables --help' for more information.
> 
> If I start with a fresh usage.db then all works:
> 
> root@OpenWrt:~# /transfer/wrtbwmon# rm /tmp/usage.db
> root@OpenWrt:~# /transfer/wrtbwmon# wrtbwmon.sh setup /tmp/usage.db
> root@OpenWrt:~# /transfer/wrtbwmon# wrtbwmon.sh update /tmp/usage.db
> root@OpenWrt:~#
> 
> But when I restore the old usage.db and try an update, then it fails again:
> 
> root@OpenWrt:~# /transfer/wrtbwmon# cp /tmp/usage.db-bak /tmp/usage.db
> root@OpenWrt:~# /transfer/wrtbwmon# wrtbwmon.sh update /tmp/usage.db
> iptables v1.4.21: host/network eth1' not found
> Tryiptables -h' or 'iptables --help' for more information.
> iptables v1.4.21: host/network eth1' not found
> Tryiptables -h' or 'iptables --help' for more information.
> 
> Has there been a change in the DB layout since JAN? If not, how can I
> merge the old and new usage.db?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/pyrovski/wrtbwmon/issues/16

## 

Peter Bailey
Mountain View, CA
Phone: (651) 538-0340

**Comment by mw446391** [comment]
ah right - just checked the old file and found the line it complained about:

#mac,ip,iface,in,out,total,first_date,last_date
eth1,NA,eth1,,2353032,2353032,17-01-2016_21:29:00,22-04-2016_00:00:01

So I guess, I could just delete this line and it should work; let me try ...

**Comment by mw446391** [comment]
Yes that worked :-)

Curious how the line for the "eth1" i/f got into the file and somehow the old version of wrtbwmon was not complaining about it.
