### ISSUE TITLE
Can't install on LEDE

### ISSUE THREAD

**Issue by FilipBB** [pyrovski/wrtbwmon#22]
The ipk won't install on LEDE:

[root@lede:~] # cat /etc/openwrt_release
DISTRIB_ID='LEDE'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r2709-b7677f0'
DISTRIB_CODENAME='reboot'
DISTRIB_TARGET='brcm47xx/mips74k'
DISTRIB_DESCRIPTION='LEDE Reboot SNAPSHOT r2709-b7677f0'
DISTRIB_TAINTS='no-all'

[root@lede:~] # opkg install ./wrtbwmon_0.35_all.ipk
Collected errors:
 * pkg_init_from_file: Malformed package file ./wrtbwmon_0.35_all.ipk.

**Comment by pyrovski** [comment]
How about [this version](https://dl.dropboxusercontent.com/u/316339/wrtbwmon_0.35_all.ipk)?

**Comment by FilipBB** [comment]
Nope, it didn't work, it's giving the same error, but I managed to figure out the problem: the control file must be compressed into control.tar.gz from it's own directory, and the final ipk file must be as well so that you have them compressed like so:

[root@lede:wrt] # bsdtar -tf ./wrtbwmon_0.35_all.ipk
./
./control.tar.gz
./data.tar.gz
./debian-binary
[root@lede:wrt] # bsdtar -tf tmp/control.tar.gz
./
./control
[root@lede:wrt] #

Notice the directory references "./"

**Comment by FilipBB** [comment]
Actually the control.tar.gz file was already zipped that way, only the final ipk wasn't.

**Comment by pyrovski** [comment]
Could you try the package at that link again? I switched to packaging with _tar_ instead of _ar_, and now I get this output:

$ bsdtar -tf wrtbwmon_0.35_all.ipk
                                                            
./debian-binary
./data.tar.gz
./control.tar.gz

**Comment by FilipBB** [comment]
Yes, it is working now, thanks.
