### ISSUE TITLE
postinst is not included in ipk

### ISSUE THREAD

**Issue by FilipBB** [pyrovski/wrtbwmon#24]
The **postinst** file is not included in the control archive of the ipk package. It sets up a useful cron job for updating the database and the web page.

Also, on openwrt there is no **wrtbwmon** user, so either one needs to be created or the cron job needs to be set up in  **/etc/cronjobs/root** instead of **/etc/cronjobs/wrtbwmon**.

**Comment by pyrovski** [comment]
The latest commit should fix the postinst issue. I'll think about creating a wrtbwmon user vs. modifying root's crontab.

**Comment by FilipBB** [comment]
Great, thanks.
