### ISSUE TITLE
iptables errors on setup

### ISSUE THREAD

**Issue by thep0stmaster** [pyrovski/wrtbwmon#26]
Linksys WRT1900AC
OpenWrt Chaos Calmer 15.05.1 / LuCI 15.05-142-gb6330a1 Release (git-15.363.78009-956be55)
 
root@connect:~# wrtbwmon.sh remove
root@connect:~# wrtbwmon.sh setup /tmp/usage.db
iptables v1.4.21: host/network `pkts' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.21: host/network `pkts' not found
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `RETURN'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `RETURN'
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.21: host/network `Chain' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.21: host/network `Chain' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.21: host/network `Zeroing' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.21: host/network `Zeroing' not found
Try `iptables -h' or 'iptables --help' for more information.
awk: can't open '': No such file or directory
root@connect:~#

What could be causing these errors?

**Comment by thep0stmaster** [comment]
root@connect:~# wrtbwmon.sh remove; rm -f /tmp/usage.db
root@connect:~# wrtbwmon.sh setup /tmp/usage.db
ERROR: /tmp/usage.db not writable
root@connect:~# wrtbwmon.sh remove; rm -f /tmp/usage.db
root@connect:~# touch /tmp/usage.db && wrtbwmon.sh setup /tmp/usage.db
iptables v1.4.21: host/network `pkts' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.21: host/network `pkts' not found
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `RETURN'
Try `iptables -h' or 'iptables --help' for more information.
Bad argument `RETURN'
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.21: host/network `Chain' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.21: host/network `Chain' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.21: host/network `Zeroing' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.4.21: host/network `Zeroing' not found
Try `iptables -h' or 'iptables --help' for more information.
awk: can't open '': No such file or directory

**Comment by pyrovski** [comment]
Can you send me the output of "iptables -nvL -t mangle"? You can also try adding "set -x" after the comment block in the wrtbwmon script and sending that output.

**Comment by pyrovski** [comment]
Closed due to inactivity.
