### ISSUE TITLE
Why Network Usage always show 0 B?

### ISSUE THREAD

**Issue by kukudemajia** [pyrovski/wrtbwmon#28]
![qq 20170524085333](https://cloud.githubusercontent.com/assets/17118600/26385267/e3f8fe9e-4070-11e7-90bd-1e6009434f85.jpg)

luci-wrtbwmon_0.5.1_all.ipk
wrtbwmon_0.36_all.ipk

**Comment by pyrovski** [comment]
This is probably a duplicate of https://github.com/pyrovski/wrtbwmon/issues/23.
