### ISSUE TITLE
Interface messed up in 18.06

### ISSUE THREAD

**Issue by RaNd250** [pyrovski/wrtbwmon#34]
The web interface inside Luci is messed up a bit, in 18.06 version.

![image](https://user-images.githubusercontent.com/6122169/46904769-243a2d00-cef2-11e8-9b1f-877cd3dc9ad2.png)

**Comment by pyrovski** [comment]
This is an issue with the frontend package: https://github.com/Kiougar/luci-wrtbwmon.
