### ISSUE TITLE
presumptions

### ISSUE THREAD

**Issue by valentt** [pyrovski/wrtbwmon#4]
First thanks for updating wrtbwmon script, it worked for me once but now it is giving me lots of errors.
I looked at your code and one thing I don't like is that you have make is to take too much presumtions and don't leave choice to users.

For example I would like to track wifi interface which is in network called also wifi, with your current script I can't do that without heavily modifying whole code.

Original script has nice variables that let users choose which interface to monitor.

Will you consider going back more to original authors idea of being more flexible?

Thanks!

**Comment by pyrovski** [comment]
You can add an interface to the `interfaces` variable in the `awk` branch. What other configuration would you like to have available?

**Comment by valentt** [comment]
I'll check out awk branch, thanks.
