### ISSUE TITLE
Problem with WAN Detection OPENWRT

### ISSUE THREAD

**Issue by drewgarth** [pyrovski/wrtbwmon#5]
Thanks for updating this script, 
Compared to the Master branch, the AWK branch seems to have a problem with the way it writes out the detected WAN into the DB file.
For debugging purposes i just ran the Master branch and then the AWK branch with the following
MASTER
(WAN),NA,eth1,46508,22835,0,0,69343,04-05-2015_08:53:33,04-05-2015_08:53:34

AWK
eth1,NA,eth1,32,1672,,,1704,04-05-2015_09:47:25,04-05-2015_09:47:25

The extra three columns result in the quotes being in the wrong placed in the array when published, and the entire table then fails to load.
Array in Javascript in AWK generated HTML
new Array("eth1",
32.000000,1672,1704,04-05-2015_09:47:25,04-05-2015_09:47:25,"",""),

Hope this helps

cheers

**Comment by pyrovski** [comment]
I think I fixed it. Would you mind testing the latest code in the awk branch? You'll have to delete your old data file.

**Comment by drewgarth** [comment]
Thanks for that. It fixed it for me.

One other question, per your instructions you haven't specified the need for a cron job to keep running setup and therefore refresh the connected MAC/hostnames?    Is this correct that i dont need to continually run setup in cron?

thanks for your work

**Comment by drewgarth** [comment]
Oops, hit the wrong button, while i think it can be closed, I will allow you to do that! :)

**Comment by pyrovski** [comment]
You should only need to run setup once after booting the machine, unless you change the list of interfaces to monitor. New hosts are automatically recognized in the update command.
